<?php

function cipher_menu() {
    $items['cipher'] = array(
        'title' => 'Cipher',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('cipher_form'),
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM
    );

    return $items;
}

function cipher_form() {
    $form['value'] = array(
        '#title' => 'Shift value',
        '#type' => 'textfield',
        '#description' => t('Please enter number to shift by.')
    );

    $form['direction'] = array(
        '#title' => 'Shift direction',
        '#type' => 'textfield',
        '#description' => t('Enter \'left\' or \'right\' for encryption direction.')
    );

    $form['phrase'] = array(
        '#title' => 'Phrase',
        '#type' => 'textfield',
        '#description' => t('Please enter phrase to be encrypted.')
    );

    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => 'Encrypt'
    );

    return $form;
}
